<a href="https://colab.research.google.com/github/felipekenjidev/performance-estudantes/blob/main/miniprojetods_performance_estudantes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Mini Projeto 2026 - Performance dos Estudantes**
O **Mini Projeto Performance dos Estudantes** é um projeto desenvolvido em Python com apoio da **Liga de Data Science da Unicamp**.

O objetivo do trabalho é analisar um dataset sobre as características dos estudantes, e gerar insights e correlações sobre as variáveis que mais impactam na performance escolar/universitária de um aluno.

**Integrantes:**
- Felipe Kenji Ouba Fukuzono
- Thiago Henrique da Silva dos Santos
- Giovanna Mota Freire
- Julia Duarte Mira Marques

## **Etapa 1 - Tratamento de Dados**
Carregar e limpar o dataset inicial, tratando possíveis valores vazios, duplicados ou discrepantes que podem atrapalhar a análise.

### **Etapa 1.1 - Download do Dataset**
Fazer o download do dataset diretamente pelo Kagglehub, com objetivo de facilitar e agilizar o projeto.

In [8]:
# Importar Bibliotecas do Python
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Baixar o Arquivo Dataset direto do Kaggle
print('--- OBTER O ARQUIVO DATASET ---')
path = kagglehub.dataset_download('devansodariya/student-performance-data')

--- OBTER O ARQUIVO DATASET ---
Using Colab cache for faster access to the 'student-performance-data' dataset.

### **Etapa 1.2 - Carregamento do Dataset**
Carregar o dataset para dentro de um dataframe, com objetivo de obter uma melhor visualização e poder manipular suas informações.

In [9]:
# Importar Bibliotecas do Python
import pandas as pd
import os

# Encontrar o Arquivo CSV
arquivo_csv = os.path.join(path, 'student_data.csv')

# Abrir o Arquivo Dataset
df = pd.read_csv(arquivo_csv)

# Exibir o DataFrame
print('--- EXIBIÇÃO DO DATASET EM FORMATO DE TABELA ---')
display(df.head())

--- EXIBIÇÃO DO DATASET EM FORMATO DE TABELA ---

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

### **Etapa 1.3 - Visualização de Valores Nulos**
Visualizar as informações do dataframe, verificando a quantidade de linhas e colunas, e verificando se há algum valor nulo.

*Ps: Como foi verificado que não há nenhum valor nulo, não houve necessidade de tratamento de valores nulos.*

In [10]:
# Verificar a Quantidade de Linhas por Colunas
print('--- QUANTIDADE DE LINHAS/COLUNAS ---')
print(df.shape)

# Exibir Nome de Todas as Colunas Presentes
print('\n--- NOME DAS COLUNAS ---')
print(df.columns)

# Exibir as Colunas e a Quantidade de Valores Presentes
print('\n--- COLUNAS E SEUS VALORES ---')
print(df.info())

# Contar o Número de Linhas com Valores Ausentes
print('\n--- DADOS DAS LINHAS ---')
print(f'Número de linhas do dataset: {len(df)}')
print(f'Número de linhas com pelo menos um valor ausente: {df.isna().sum().sum()}')

--- QUANTIDADE DE LINHAS/COLUNAS ---
(395, 33)

--- NOME DAS COLUNAS ---
Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='object')

--- COLUNAS E SEUS VALORES ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher      395 non-null    object
 21  internet    395 non-null    object
 22  romantic    395 non-null    object
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  G1          395 non-null    int64
 31  G2          395 non-null    int64
 32  G3          395 non-null    int64
dtypes: int64(16), object(17)
memory usage: 102.0+ KB
None

--- DADOS DAS LINHAS ---
Número de linhas do dataset: 395
Número de linhas com pelo menos um valor ausente: 0

### **Etapa 1.4 - Visualização de Valores Duplicados**
Verificar as informações do dataframe, observando se há algum valor duplicado discrepante, que pode atrapalhar as análises, no dataframe.

*Ps: Como foi verificado que não há nenhum valor repetido, não houve necessidade de tratamento.*

In [11]:
# Identificar Linhas Duplicadas no Dataframe
num_duplicadas = df.duplicated().sum()

# Exibir o Número de Linhas Duplicadas
print('--- EXIBIÇÃO DE LINHAS DUPLICADAS ---')
if num_duplicadas > 0:
    print('Primeiras 5 linhas duplicadas (mantendo a primeira ocorrência):')
    display(df[df.duplicated()].head())
else:
    print('Não há linhas duplicadas para exibir.')

--- EXIBIÇÃO DE LINHAS DUPLICADAS ---
Não há linhas duplicadas para exibir.

### **Etapa 1.5 - Verificação de Frequência de Categorias**
Verificar a frequência de cada categoria do dataframe, com objetivo de encontrar possíveis valores, com frequências extremamente baixas, que poluem o dataset.

*Ps: Utilizando como referência um α = 5%, existe somente uma categoria que está abaixo do limite proposto, a Fjob_health. Como não existe mais nenhuma categoria abaixo do limite, que poluem o dataset, não há motivos para tratá-los.*

In [12]:
# Declarar Variável das Colunas Categóricas
colunas_alvo = ['Mjob', 'Fjob', 'reason', 'guardian']

# Exibir a Frequência de Cada Categoria das Colunas Categóricas
print('--- EXIBIÇÃO DE FREQUÊNCIA DE CATEGORIAS ---')
for coluna in colunas_alvo:
  print(f'{df[coluna].value_counts(normalize=True)}\n')

--- EXIBIÇÃO DE FREQUÊNCIA DE CATEGORIAS ---
Mjob
other       0.356962
services    0.260759
at_home     0.149367
teacher     0.146835
health      0.086076
Name: proportion, dtype: float64

Fjob
other       0.549367
services    0.281013
teacher     0.073418
at_home     0.050633
health      0.045570
Name: proportion, dtype: float64

reason
course        0.367089
home          0.275949
reputation    0.265823
other         0.091139
Name: proportion, dtype: float64

guardian
mother    0.691139
father    0.227848
other     0.081013
Name: proportion, dtype: float64

### **Etapa 1.6 - Identificação de Colunas com Variância Quase Zero**
Fazer código para analisar variância de todas as coluna (ou fazer value_count). Se alguma coluna tiver mais de 95% das respostas concentradas numa única opção (ex: 96% dos alunos pertencem à mesma escola), essa coluna não tem poder de diferenciação

Foi avaliado que as colunas **higher**, **Pstatus** e **school** serão **excluídas** tanto da modelagem preditiva (Machine Learning) quanto das análises visuais e geração de gráficos.

A decisão de descartar completamente estas variáveis baseia-se no critério estatístico de Variância Quase Zero. Dados excessivamente concentrados em uma única resposta perdem o poder de diferenciação, o que significa que:

- Para os modelos de ML: Elas não acrescentam valor para que o algoritmo aprenda os padrões de comportamento dos estudantes.

- Para os gráficos: Qualquer cruzamento visual gerará plots severamente desproporcionais e distorcidos, impossibilitando comparações justas ou a extração de insights que sejam estatisticamente confiáveis devido à falta de dados no grupo minoritário.

Abaixo detalha-se a justificativa técnica para a exclusão total de cada uma delas:

-  **higher** (Ambição de frequentar o Ensino Superior): 94,94% dos alunos responderam "SIM" (375 estudantes contra apenas 20 que responderam "não"). Como a esmagadora maioria tem o mesmo objetivo, esta variável comporta-se praticamente como uma constante no dataset. Nos gráficos, a sub-representação extrema (apenas 20 pessoas) tornaria qualquer comparação de notas visualmente desequilibrada e sem relevância científica.

- **Pstatus** (Status de união dos pais): 89,62% dos pais dos alunos vivem juntos (354 casos). Com apenas 10,38% (41 alunos) de pais separados, a amostra é muito pequena. Tentar cruzar essa variável graficamente com a qualidade da relação familiar ou com as notas geraria gráficos enganosos, pois não há dados volumosos o suficiente do grupo de pais separados para confrontar com o grupo majoritário.

- **school** (Escola de origem do estudante): Esta coluna apresenta 88,35% dos dados concentrados na escola GP (349 alunos contra apenas 46 da escola MS). Devido a esse forte desbalanceamento populacional, manter a variável na análise induziria a gerar gráficos que refletem quase exclusivamente o padrão de uma das instituições. Como a escola MS está severamente sub-representada, o parâmetro escolar torna-se irrelevante para traçar paralelos visuais ou preditivos gerais.

In [17]:
print('--- ANÁLISE DE TENDÊNCIAS E PROPORÇÃO DE RESPOSTAS (TODAS AS COLUNAS) ---\n')

# Vamos percorrer todas as colunas do dataset automaticamente
for coluna in df.columns:
    print(f"==================================================")
    print(f"COLUNA: {coluna.upper()}")
    print(f"==================================================")

    # 1. Conta a quantidade absoluta de cada resposta
    contagem = df[coluna].value_counts()

    # 2. Calcula a porcentagem de cada resposta (multiplicamos por 100 e arredondamos)
    porcentagem = df[coluna].value_counts(normalize=True) * 100

    # 3. Junta as duas informações em um novo DataFrame para exibir bonitinho lado a lado
    analise_coluna = pd.DataFrame({
        'Quantidade': contagem,
        'Porcentagem (%)': porcentagem.round(2)
    })

    display(analise_coluna)
    print("\n") # Dá um espaço entre as colunas para não virar bagunça

--- ANÁLISE DE TENDÊNCIAS E PROPORÇÃO DE RESPOSTAS (TODAS AS COLUNAS) ---

==================================================
COLUNA: SCHOOL
==================================================

        Quantidade  Porcentagem (%)
school
GP             349            88.35
MS              46            11.65

==================================================
COLUNA: SEX
==================================================

     Quantidade  Porcentagem (%)
sex
F           208            52.66
M           187            47.34

==================================================
COLUNA: AGE
==================================================

     Quantidade  Porcentagem (%)
age
16          104            26.33
17           98            24.81
18           82            20.76
15           82            20.76
19           24             6.08
20            3             0.76
22            1             0.25
21            1             0.25

==================================================
COLUNA: ADDRESS
==================================================

         Quantidade  Porcentagem (%)
address
U               307            77.72
R                88            22.28

==================================================
COLUNA: FAMSIZE
==================================================

         Quantidade  Porcentagem (%)
famsize
GT3             281            71.14
LE3             114            28.86

==================================================
COLUNA: PSTATUS
==================================================

         Quantidade  Porcentagem (%)
Pstatus
T               354            89.62
A                41            10.38

==================================================
COLUNA: MEDU
==================================================

      Quantidade  Porcentagem (%)
Medu
4            131            33.16
2            103            26.08
3             99            25.06
1             59            14.94
0              3             0.76

==================================================
COLUNA: FEDU
==================================================

      Quantidade  Porcentagem (%)
Fedu
2            115            29.11
3            100            25.32
4             96            24.30
1             82            20.76
0              2             0.51

==================================================
COLUNA: MJOB
==================================================

          Quantidade  Porcentagem (%)
Mjob
other            141            35.70
services         103            26.08
at_home           59            14.94
teacher           58            14.68
health            34             8.61

==================================================
COLUNA: FJOB
==================================================

          Quantidade  Porcentagem (%)
Fjob
other            217            54.94
services         111            28.10
teacher           29             7.34
at_home           20             5.06
health            18             4.56

==================================================
COLUNA: REASON
==================================================

            Quantidade  Porcentagem (%)
reason
course             145            36.71
home               109            27.59
reputation         105            26.58
other               36             9.11

==================================================
COLUNA: GUARDIAN
==================================================

          Quantidade  Porcentagem (%)
guardian
mother           273            69.11
father            90            22.78
other             32             8.10

==================================================
COLUNA: TRAVELTIME
==================================================

            Quantidade  Porcentagem (%)
traveltime
1                  257            65.06
2                  107            27.09
3                   23             5.82
4                    8             2.03

==================================================
COLUNA: STUDYTIME
==================================================

           Quantidade  Porcentagem (%)
studytime
2                 198            50.13
1                 105            26.58
3                  65            16.46
4                  27             6.84

==================================================
COLUNA: FAILURES
==================================================

          Quantidade  Porcentagem (%)
failures
0                312            78.99
1                 50            12.66
2                 17             4.30
3                 16             4.05

==================================================
COLUNA: SCHOOLSUP
==================================================

           Quantidade  Porcentagem (%)
schoolsup
no                344            87.09
yes                51            12.91

==================================================
COLUNA: FAMSUP
==================================================

        Quantidade  Porcentagem (%)
famsup
yes            242            61.27
no             153            38.73

==================================================
COLUNA: PAID
==================================================

      Quantidade  Porcentagem (%)
paid
no           214            54.18
yes          181            45.82

==================================================
COLUNA: ACTIVITIES
==================================================

            Quantidade  Porcentagem (%)
activities
yes                201            50.89
no                 194            49.11

==================================================
COLUNA: NURSERY
==================================================

         Quantidade  Porcentagem (%)
nursery
yes             314            79.49
no               81            20.51

==================================================
COLUNA: HIGHER
==================================================

        Quantidade  Porcentagem (%)
higher
yes            375            94.94
no              20             5.06

==================================================
COLUNA: INTERNET
==================================================

          Quantidade  Porcentagem (%)
internet
yes              329            83.29
no                66            16.71

==================================================
COLUNA: ROMANTIC
==================================================

          Quantidade  Porcentagem (%)
romantic
no               263            66.58
yes              132            33.42

==================================================
COLUNA: FAMREL
==================================================

        Quantidade  Porcentagem (%)
famrel
4              195            49.37
5              106            26.84
3               68            17.22
2               18             4.56
1                8             2.03

==================================================
COLUNA: FREETIME
==================================================

          Quantidade  Porcentagem (%)
freetime
3                157            39.75
4                115            29.11
2                 64            16.20
5                 40            10.13
1                 19             4.81

==================================================
COLUNA: GOOUT
==================================================

       Quantidade  Porcentagem (%)
goout
3             130            32.91
2             103            26.08
4              86            21.77
5              53            13.42
1              23             5.82

==================================================
COLUNA: DALC
==================================================

      Quantidade  Porcentagem (%)
Dalc
1            276            69.87
2             75            18.99
3             26             6.58
5              9             2.28
4              9             2.28

==================================================
COLUNA: WALC
==================================================

      Quantidade  Porcentagem (%)
Walc
1            151            38.23
2             85            21.52
3             80            20.25
4             51            12.91
5             28             7.09

==================================================
COLUNA: HEALTH
==================================================

        Quantidade  Porcentagem (%)
health
5              146            36.96
3               91            23.04
4               66            16.71
1               47            11.90
2               45            11.39

==================================================
COLUNA: ABSENCES
==================================================

          Quantidade  Porcentagem (%)
absences
0                115            29.11
2                 65            16.46
4                 53            13.42
6                 31             7.85
8                 22             5.57
10                17             4.30
14                12             3.04
12                12             3.04
3                  8             2.03
7                  7             1.77
16                 7             1.77
18                 5             1.27
5                  5             1.27
20                 4             1.01
13                 3             0.76
15                 3             0.76
1                  3             0.76
22                 3             0.76
9                  3             0.76
11                 3             0.76
28                 1             0.25
24                 1             0.25
54                 1             0.25
25                 1             0.25
56                 1             0.25
26                 1             0.25
75                 1             0.25
21                 1             0.25
19                 1             0.25
30                 1             0.25
38                 1             0.25
40                 1             0.25
23                 1             0.25
17                 1             0.25

==================================================
COLUNA: G1
==================================================

    Quantidade  Porcentagem (%)
G1
10          51            12.91
8           41            10.38
11          39             9.87
7           37             9.37
12          35             8.86
13          33             8.35
9           31             7.85
14          30             7.59
15          24             6.08
6           24             6.08
16          22             5.57
18           8             2.03
17           8             2.03
5            7             1.77
19           3             0.76
4            1             0.25
3            1             0.25

==================================================
COLUNA: G2
==================================================

    Quantidade  Porcentagem (%)
G2
9           50            12.66
10          46            11.65
12          41            10.38
13          37             9.37
11          35             8.86
15          34             8.61
8           32             8.10
14          23             5.82
7           21             5.32
5           15             3.80
6           14             3.54
0           13             3.29
16          13             3.29
18          12             3.04
17           5             1.27
19           3             0.76
4            1             0.25

==================================================
COLUNA: G3
==================================================

    Quantidade  Porcentagem (%)
G3
10          56            14.18
11          47            11.90
0           38             9.62
15          33             8.35
8           32             8.10
12          31             7.85
13          31             7.85
9           28             7.09
14          27             6.84
16          16             4.05
6           15             3.80
18          12             3.04
7            9             2.28
5            7             1.77
17           6             1.52
19           5             1.27
20           1             0.25
4            1             0.25